# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_changePasswdWidget(object):
    def setupUi(self, changePasswdWidget):
        changePasswdWidget.setObjectName("changePasswdWidget")
        changePasswdWidget.resize(530, 282)
        changePasswdWidget.setStyleSheet("QPushButton:hover { color: red }")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(changePasswdWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(changePasswdWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.passwdLine = QtWidgets.QLineEdit(changePasswdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwdLine.sizePolicy().hasHeightForWidth())
        self.passwdLine.setSizePolicy(sizePolicy)
        self.passwdLine.setObjectName("passwdLine")
        self.horizontalLayout.addWidget(self.passwdLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cacelButton = QtWidgets.QPushButton(changePasswdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cacelButton.sizePolicy().hasHeightForWidth())
        self.cacelButton.setSizePolicy(sizePolicy)
        self.cacelButton.setObjectName("cacelButton")
        self.horizontalLayout_2.addWidget(self.cacelButton)
        self.sureButton = QtWidgets.QPushButton(changePasswdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sureButton.sizePolicy().hasHeightForWidth())
        self.sureButton.setSizePolicy(sizePolicy)
        self.sureButton.setObjectName("sureButton")
        self.horizontalLayout_2.addWidget(self.sureButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(changePasswdWidget)
        QtCore.QMetaObject.connectSlotsByName(changePasswdWidget)

    def retranslateUi(self, changePasswdWidget):
        _translate = QtCore.QCoreApplication.translate
        changePasswdWidget.setWindowTitle(_translate("changePasswdWidget", "密码修改"))
        self.label.setText(_translate("changePasswdWidget", "新密码"))
        self.cacelButton.setText(_translate("changePasswdWidget", "取消"))
        self.sureButton.setText(_translate("changePasswdWidget", "确定"))
