# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handleUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_handleUserWidget(object):
    def setupUi(self, handleUserWidget):
        handleUserWidget.setObjectName("handleUserWidget")
        handleUserWidget.resize(492, 262)
        handleUserWidget.setStyleSheet("QPushButton:hover { color: red }")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(handleUserWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delUserButton = QtWidgets.QPushButton(handleUserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delUserButton.sizePolicy().hasHeightForWidth())
        self.delUserButton.setSizePolicy(sizePolicy)
        self.delUserButton.setObjectName("delUserButton")
        self.horizontalLayout.addWidget(self.delUserButton, 0, QtCore.Qt.AlignRight)
        self.updateUserButton = QtWidgets.QPushButton(handleUserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateUserButton.sizePolicy().hasHeightForWidth())
        self.updateUserButton.setSizePolicy(sizePolicy)
        self.updateUserButton.setObjectName("updateUserButton")
        self.horizontalLayout.addWidget(self.updateUserButton)
        self.changePasswdButton = QtWidgets.QPushButton(handleUserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changePasswdButton.sizePolicy().hasHeightForWidth())
        self.changePasswdButton.setSizePolicy(sizePolicy)
        self.changePasswdButton.setObjectName("changePasswdButton")
        self.horizontalLayout.addWidget(self.changePasswdButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(handleUserWidget)
        QtCore.QMetaObject.connectSlotsByName(handleUserWidget)

    def retranslateUi(self, handleUserWidget):
        _translate = QtCore.QCoreApplication.translate
        handleUserWidget.setWindowTitle(_translate("handleUserWidget", "Form"))
        self.delUserButton.setText(_translate("handleUserWidget", "删除"))
        self.updateUserButton.setText(_translate("handleUserWidget", "编辑"))
        self.changePasswdButton.setText(_translate("handleUserWidget", "重置密码"))
