# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateUserWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_updateUserWidget(object):
    def setupUi(self, updateUserWidget):
        updateUserWidget.setObjectName("updateUserWidget")
        updateUserWidget.resize(694, 336)
        updateUserWidget.setStyleSheet("QPushButton:hover { color: red }")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(updateUserWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(updateUserWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.userLine = QtWidgets.QLineEdit(updateUserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userLine.sizePolicy().hasHeightForWidth())
        self.userLine.setSizePolicy(sizePolicy)
        self.userLine.setObjectName("userLine")
        self.gridLayout.addWidget(self.userLine, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(updateUserWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.roleComboBox = QtWidgets.QComboBox(updateUserWidget)
        self.roleComboBox.setObjectName("roleComboBox")
        self.gridLayout.addWidget(self.roleComboBox, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cacleButton = QtWidgets.QPushButton(updateUserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cacleButton.sizePolicy().hasHeightForWidth())
        self.cacleButton.setSizePolicy(sizePolicy)
        self.cacleButton.setObjectName("cacleButton")
        self.horizontalLayout.addWidget(self.cacleButton)
        self.sureButton = QtWidgets.QPushButton(updateUserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sureButton.sizePolicy().hasHeightForWidth())
        self.sureButton.setSizePolicy(sizePolicy)
        self.sureButton.setObjectName("sureButton")
        self.horizontalLayout.addWidget(self.sureButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(updateUserWidget)
        QtCore.QMetaObject.connectSlotsByName(updateUserWidget)

    def retranslateUi(self, updateUserWidget):
        _translate = QtCore.QCoreApplication.translate
        updateUserWidget.setWindowTitle(_translate("updateUserWidget", "修改用户信息"))
        self.label.setText(_translate("updateUserWidget", "用户名"))
        self.label_2.setText(_translate("updateUserWidget", "角色名"))
        self.cacleButton.setText(_translate("updateUserWidget", "取消"))
        self.sureButton.setText(_translate("updateUserWidget", "确定"))
