# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userWidget(object):
    def setupUi(self, userWidget):
        userWidget.setObjectName("userWidget")
        userWidget.resize(583, 330)
        self.horizontalLayout = QtWidgets.QHBoxLayout(userWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listUserWidgeUserTable = QtWidgets.QTableWidget(userWidget)
        self.listUserWidgeUserTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listUserWidgeUserTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listUserWidgeUserTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listUserWidgeUserTable.setObjectName("listUserWidgeUserTable")
        self.listUserWidgeUserTable.setColumnCount(5)
        self.listUserWidgeUserTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.listUserWidgeUserTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listUserWidgeUserTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listUserWidgeUserTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.listUserWidgeUserTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.listUserWidgeUserTable.setHorizontalHeaderItem(4, item)
        self.listUserWidgeUserTable.horizontalHeader().setCascadingSectionResizes(True)
        self.listUserWidgeUserTable.horizontalHeader().setDefaultSectionSize(100)
        self.listUserWidgeUserTable.horizontalHeader().setSortIndicatorShown(False)
        self.listUserWidgeUserTable.verticalHeader().setDefaultSectionSize(60)
        self.verticalLayout.addWidget(self.listUserWidgeUserTable)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(userWidget)
        QtCore.QMetaObject.connectSlotsByName(userWidget)

    def retranslateUi(self, userWidget):
        _translate = QtCore.QCoreApplication.translate
        userWidget.setWindowTitle(_translate("userWidget", "用户信息"))
        self.listUserWidgeUserTable.setSortingEnabled(True)
        item = self.listUserWidgeUserTable.horizontalHeaderItem(0)
        item.setText(_translate("userWidget", "用户id"))
        item = self.listUserWidgeUserTable.horizontalHeaderItem(1)
        item.setText(_translate("userWidget", "用户名"))
        item = self.listUserWidgeUserTable.horizontalHeaderItem(2)
        item.setText(_translate("userWidget", "角色id"))
        item = self.listUserWidgeUserTable.horizontalHeaderItem(3)
        item.setText(_translate("userWidget", "角色名"))
        item = self.listUserWidgeUserTable.horizontalHeaderItem(4)
        item.setText(_translate("userWidget", "操作"))
