# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addAppWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addAppWidget(object):
    def setupUi(self, addAppWidget):
        addAppWidget.setObjectName("addAppWidget")
        addAppWidget.resize(560, 355)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(addAppWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(150, -1, 150, -1)
        self.gridLayout.setSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(addAppWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.appLine = QtWidgets.QLineEdit(addAppWidget)
        self.appLine.setObjectName("appLine")
        self.gridLayout.addWidget(self.appLine, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(addAppWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.projectNameCombox = QtWidgets.QComboBox(addAppWidget)
        self.projectNameCombox.setObjectName("projectNameCombox")
        self.gridLayout.addWidget(self.projectNameCombox, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cacelButton = QtWidgets.QPushButton(addAppWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cacelButton.sizePolicy().hasHeightForWidth())
        self.cacelButton.setSizePolicy(sizePolicy)
        self.cacelButton.setObjectName("cacelButton")
        self.horizontalLayout.addWidget(self.cacelButton, 0, QtCore.Qt.AlignRight)
        self.sureButton = QtWidgets.QPushButton(addAppWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sureButton.sizePolicy().hasHeightForWidth())
        self.sureButton.setSizePolicy(sizePolicy)
        self.sureButton.setObjectName("sureButton")
        self.horizontalLayout.addWidget(self.sureButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(addAppWidget)
        QtCore.QMetaObject.connectSlotsByName(addAppWidget)

    def retranslateUi(self, addAppWidget):
        _translate = QtCore.QCoreApplication.translate
        addAppWidget.setWindowTitle(_translate("addAppWidget", "新增app"))
        self.label.setText(_translate("addAppWidget", "应用名字"))
        self.label_2.setText(_translate("addAppWidget", "项目名字"))
        self.cacelButton.setText(_translate("addAppWidget", "取消"))
        self.sureButton.setText(_translate("addAppWidget", "确定"))
