# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appHandleButtons.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_appHandleButtons(object):
    def setupUi(self, appHandleButtons):
        appHandleButtons.setObjectName("appHandleButtons")
        appHandleButtons.resize(509, 311)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(appHandleButtons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fabuButton = QtWidgets.QPushButton(appHandleButtons)
        self.fabuButton.setObjectName("fabuButton")
        self.horizontalLayout.addWidget(self.fabuButton)
        self.restartButton = QtWidgets.QPushButton(appHandleButtons)
        self.restartButton.setObjectName("restartButton")
        self.horizontalLayout.addWidget(self.restartButton)
        self.startButton = QtWidgets.QPushButton(appHandleButtons)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(appHandleButtons)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(appHandleButtons)
        QtCore.QMetaObject.connectSlotsByName(appHandleButtons)

    def retranslateUi(self, appHandleButtons):
        _translate = QtCore.QCoreApplication.translate
        appHandleButtons.setWindowTitle(_translate("appHandleButtons", "Form"))
        self.fabuButton.setText(_translate("appHandleButtons", "发布"))
        self.restartButton.setText(_translate("appHandleButtons", "重启"))
        self.startButton.setText(_translate("appHandleButtons", "启动"))
        self.stopButton.setText(_translate("appHandleButtons", "停止"))
