# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delAppWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delAppWidget(object):
    def setupUi(self, delAppWidget):
        delAppWidget.setObjectName("delAppWidget")
        delAppWidget.resize(464, 343)
        self.horizontalLayout = QtWidgets.QHBoxLayout(delAppWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delAppButton = QtWidgets.QPushButton(delAppWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delAppButton.sizePolicy().hasHeightForWidth())
        self.delAppButton.setSizePolicy(sizePolicy)
        self.delAppButton.setObjectName("delAppButton")
        self.horizontalLayout.addWidget(self.delAppButton, 0, QtCore.Qt.AlignLeft)

        self.retranslateUi(delAppWidget)
        QtCore.QMetaObject.connectSlotsByName(delAppWidget)

    def retranslateUi(self, delAppWidget):
        _translate = QtCore.QCoreApplication.translate
        delAppWidget.setWindowTitle(_translate("delAppWidget", "Form"))
        self.delAppButton.setText(_translate("delAppWidget", "删除"))
