# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fabuWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fabuWidget(object):
    def setupUi(self, fabuWidget):
        fabuWidget.setObjectName("fabuWidget")
        fabuWidget.resize(732, 377)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(fabuWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(150, -1, 20, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(fabuWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(fabuWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.gitCombox = QtWidgets.QComboBox(fabuWidget)
        self.gitCombox.setObjectName("gitCombox")
        self.horizontalLayout_3.addWidget(self.gitCombox)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(150, -1, 150, -1)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(fabuWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gitLine = QtWidgets.QLineEdit(fabuWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gitLine.sizePolicy().hasHeightForWidth())
        self.gitLine.setSizePolicy(sizePolicy)
        self.gitLine.setObjectName("gitLine")
        self.horizontalLayout_2.addWidget(self.gitLine)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cacelButton = QtWidgets.QPushButton(fabuWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cacelButton.sizePolicy().hasHeightForWidth())
        self.cacelButton.setSizePolicy(sizePolicy)
        self.cacelButton.setObjectName("cacelButton")
        self.horizontalLayout.addWidget(self.cacelButton, 0, QtCore.Qt.AlignRight)
        self.sureButton = QtWidgets.QPushButton(fabuWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sureButton.sizePolicy().hasHeightForWidth())
        self.sureButton.setSizePolicy(sizePolicy)
        self.sureButton.setObjectName("sureButton")
        self.horizontalLayout.addWidget(self.sureButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(fabuWidget)
        QtCore.QMetaObject.connectSlotsByName(fabuWidget)

    def retranslateUi(self, fabuWidget):
        _translate = QtCore.QCoreApplication.translate
        fabuWidget.setWindowTitle(_translate("fabuWidget", "发布操作"))
        self.label.setText(_translate("fabuWidget", "选择git"))
        self.comboBox.setItemText(0, _translate("fabuWidget", "git分支"))
        self.comboBox.setItemText(1, _translate("fabuWidget", "gitTag"))
        self.label_2.setText(_translate("fabuWidget", "git信息"))
        self.cacelButton.setText(_translate("fabuWidget", "取消"))
        self.sureButton.setText(_translate("fabuWidget", "确定"))
