# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listAppWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_listApp(object):
    def setupUi(self, listApp):
        listApp.setObjectName("listApp")
        listApp.resize(621, 373)
        self.horizontalLayout = QtWidgets.QHBoxLayout(listApp)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addAppButton = QtWidgets.QPushButton(listApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAppButton.sizePolicy().hasHeightForWidth())
        self.addAppButton.setSizePolicy(sizePolicy)
        self.addAppButton.setObjectName("addAppButton")
        self.verticalLayout.addWidget(self.addAppButton)
        self.appTable = QtWidgets.QTableWidget(listApp)
        self.appTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.appTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.appTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.appTable.setObjectName("appTable")
        self.appTable.setColumnCount(4)
        self.appTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.appTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.appTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.appTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.appTable.setHorizontalHeaderItem(3, item)
        self.appTable.verticalHeader().setDefaultSectionSize(60)
        self.verticalLayout.addWidget(self.appTable)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(listApp)
        QtCore.QMetaObject.connectSlotsByName(listApp)

    def retranslateUi(self, listApp):
        _translate = QtCore.QCoreApplication.translate
        listApp.setWindowTitle(_translate("listApp", "Form"))
        self.addAppButton.setText(_translate("listApp", "新增app"))
        self.appTable.setSortingEnabled(True)
        item = self.appTable.horizontalHeaderItem(0)
        item.setText(_translate("listApp", "应用Id"))
        item = self.appTable.horizontalHeaderItem(1)
        item.setText(_translate("listApp", "应用名"))
        item = self.appTable.horizontalHeaderItem(2)
        item.setText(_translate("listApp", "项目名"))
        item = self.appTable.horizontalHeaderItem(3)
        item.setText(_translate("listApp", "操作"))
