# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handleWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_handleWidget(object):
    def setupUi(self, handleWidget):
        handleWidget.setObjectName("handleWidget")
        handleWidget.resize(595, 271)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(handleWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.updateMemButton = QtWidgets.QPushButton(handleWidget)
        self.updateMemButton.setObjectName("updateMemButton")
        self.horizontalLayout.addWidget(self.updateMemButton, 0, QtCore.Qt.AlignRight)
        self.updateAppButton = QtWidgets.QPushButton(handleWidget)
        self.updateAppButton.setObjectName("updateAppButton")
        self.horizontalLayout.addWidget(self.updateAppButton)
        self.updateFabuButton = QtWidgets.QPushButton(handleWidget)
        self.updateFabuButton.setObjectName("updateFabuButton")
        self.horizontalLayout.addWidget(self.updateFabuButton)
        self.pushButton = QtWidgets.QPushButton(handleWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.delRoleButton = QtWidgets.QPushButton(handleWidget)
        self.delRoleButton.setObjectName("delRoleButton")
        self.horizontalLayout.addWidget(self.delRoleButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(handleWidget)
        QtCore.QMetaObject.connectSlotsByName(handleWidget)

    def retranslateUi(self, handleWidget):
        _translate = QtCore.QCoreApplication.translate
        handleWidget.setWindowTitle(_translate("handleWidget", "Form"))
        self.updateMemButton.setText(_translate("handleWidget", "修改菜单权限"))
        self.updateAppButton.setText(_translate("handleWidget", "修改app管理权限"))
        self.updateFabuButton.setText(_translate("handleWidget", "修改发布权限"))
        self.pushButton.setText(_translate("handleWidget", "修改cmdb管理权限"))
        self.delRoleButton.setText(_translate("handleWidget", "删除"))
