# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roleMangleWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_roleMangeWidget(object):
    def setupUi(self, roleMangeWidget):
        roleMangeWidget.setObjectName("roleMangeWidget")
        roleMangeWidget.resize(843, 542)
        self.horizontalLayout = QtWidgets.QHBoxLayout(roleMangeWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addRoleButton = QtWidgets.QPushButton(roleMangeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addRoleButton.sizePolicy().hasHeightForWidth())
        self.addRoleButton.setSizePolicy(sizePolicy)
        self.addRoleButton.setObjectName("addRoleButton")
        self.verticalLayout.addWidget(self.addRoleButton)
        self.tableWidget = QtWidgets.QTableWidget(roleMangeWidget)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.verticalHeader().setDefaultSectionSize(60)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(roleMangeWidget)
        QtCore.QMetaObject.connectSlotsByName(roleMangeWidget)

    def retranslateUi(self, roleMangeWidget):
        _translate = QtCore.QCoreApplication.translate
        roleMangeWidget.setWindowTitle(_translate("roleMangeWidget", "roleMange"))
        self.addRoleButton.setText(_translate("roleMangeWidget", "创建角色"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("roleMangeWidget", "角色id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("roleMangeWidget", "角色名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("roleMangeWidget", "操作"))
